Products: endpoints in ProductController and domain (Product and ProductDto)
pplutap/jdp-2012-01 pull request #1
Opened 2020-12-16 16:56 UTC by BarcaLS

2020-12-16 17:54 UTC, pplutap requested changes

2020-12-16 17:54 UTC, pplutap commented on build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.16'
Powinien istnieć tylko jeden taki wpis/zależność

2020-12-16 17:54 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +@Entity(name = "products")
Tworzenie encji to osobne zadanie, usuń ją proszę

2020-12-16 19:08 UTC, BarcaLS commented
Dzięki, wprowadziłem zmiany :)

2020-12-16 20:18 UTC, pplutap commented
> Dzięki, wprowadziłem zmiany :)

Została jeszcze encja Product

2020-12-16 20:40 UTC, BarcaLS commented
Zabij mnie ale nie widzę, w klasie Product nie ma już encji.

2020-12-16 21:46 UTC, pplutap commented
Usuń proszę całą klasę Product

śr., 16 gru 2020 o 21:40 Barca <notifications@github.com> napisał(a):

> Zabij mnie ale nie widzę, w klasie Product nie ma już encji.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/pplutap/jdp-2012-01/pull/1#issuecomment-746980174>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACPUUJYBVNQTLN4P4B22M2LSVELNLANCNFSM4U6JEAOQ>
> .
>

2020-12-17 07:07 UTC, BarcaLS commented
O ja niedomyślny :) Usunąłem klasę Product.

2020-12-18 19:56 UTC, pplutap commented
Branch ma konflikty, sprawdź proszę

2020-12-18 21:06 UTC, merged