Encja Order - implementation
pplutap/jdp-2012-01 pull request #10
Opened 2020-12-19 21:07 UTC by KamilJozefowski

Wysłałem kod lecz nie jestem wstanie stwierdzić w 100% czy jest poprawny ponieważ klasa Product jeszcze nie istnieje

2020-12-21 15:04 UTC, pplutap requested changes

2020-12-21 15:04 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private long id;
ID powinno być typu obiektowego - jeśli obiekt nie został utworzony, wartością powinien być null

2020-12-27 20:54 UTC, pplutap approved these changes

2021-01-05 11:50 UTC, CezaryJanicki approved these changes

2021-01-05 22:41 UTC, CezaryJanicki approved these changes

2021-01-06 11:56 UTC, CezaryJanicki commented
Mysle ze mozesz juz mergowac.

2021-01-09 20:48 UTC, merged