ProductController - real implementation
pplutap/jdp-2012-01 pull request #18
Opened 2021-01-01 13:32 UTC by BarcaLS

2021-01-02 17:12 UTC, pplutap approved these changes

2021-01-02 17:55 UTC, CezaryJanicki approved these changes

2021-01-02 17:56 UTC, pplutap requested changes
Branch na konflikt, popraw proszę

2021-01-02 19:07 UTC, BarcaLS reviewed
Rozwiązane, proszę o merge do main.

2021-01-04 17:56 UTC, CezaryJanicki commented
teraz sa konflikty po moim zmergowaniu :)

2021-01-04 18:25 UTC, KamilJozefowski approved these changes
Wszystko ok

2021-01-04 18:31 UTC, BarcaLS commented
Dzięki za usunięcie konfliktu, dla mnie wszystko OK.

2021-01-04 18:32 UTC, CezaryJanicki approved these changes

2021-01-04 19:47 UTC, pplutap approved these changes

2021-01-04 20:03 UTC, merged